---
language: node_js
node_js:
- '0.10'
script: npm test
notifications:
  irc: irc.freenode.org#fbp
env:
  global:
  - secure: ! 'l4L3iM8eLXivwobofI/hXWaANmB3rZfyISZufXJT/FEVkPo6oGR5v5+lqCyb

      Gr8//J42FrVaEh4ulcK223nkuulQk8iuVR5Wcg0JYXNuqjI/arY/MzcsAOQP

      intVUmzqCyc9frj6lLAo4+wcX1HoP/G+n1x4uGMV0PgIFtBPMOU='
  - secure: ! 'J3AhDf/0yHEOLw2zyuja41Yeq2jqR7jn9oo2T/CY+0XUO+AzG5BkhXDr3hnV

      K3e7dkPlax1vvadqdbHE2zf/oGIeuNeGTb4uqXjfuyWWQxSTw1rGP8X5DChV

      nbvuexQFHg3NAdX7VEg4AvyLaIEicaxO4IPRPvuMgLakbVxRRHQ='
